# Generated by Django 5.2.8 on 2025-11-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "authorid",
                    models.AutoField(
                        db_column="AuthorID", primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(db_column="FirstName", max_length=100)),
                ("lastname", models.CharField(db_column="LastName", max_length=100)),
                (
                    "birthdate",
                    models.DateField(blank=True, db_column="BirthDate", null=True),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, db_column="Nationality", max_length=100, null=True
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, db_column="Biography", null=True),
                ),
            ],
            options={
                "db_table": "author",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookid",
                    models.AutoField(
                        db_column="BookID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="Title", max_length=200)),
                (
                    "isbn",
                    models.CharField(db_column="ISBN", max_length=13, unique=True),
                ),
                (
                    "publicationyear",
                    models.TextField(
                        blank=True, db_column="PublicationYear", null=True
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, db_column="Genre", max_length=100, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, db_column="Language", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookedition",
            fields=[
                (
                    "editionid",
                    models.AutoField(
                        db_column="EditionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "editionnumber",
                    models.PositiveIntegerField(
                        blank=True, db_column="EditionNumber", null=True
                    ),
                ),
                (
                    "printrun",
                    models.PositiveIntegerField(
                        blank=True, db_column="PrintRun", null=True
                    ),
                ),
                (
                    "releasedate",
                    models.DateField(blank=True, db_column="ReleaseDate", null=True),
                ),
            ],
            options={
                "db_table": "bookedition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookorder",
            fields=[
                (
                    "orderid",
                    models.AutoField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                ("orderdate", models.DateTimeField(db_column="OrderDate")),
                (
                    "totalamount",
                    models.DecimalField(
                        blank=True,
                        db_column="TotalAmount",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "paymentstatus",
                    models.CharField(
                        blank=True, db_column="PaymentStatus", max_length=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "bookorder",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookorderitem",
            fields=[
                (
                    "orderitemid",
                    models.AutoField(
                        db_column="OrderItemID", primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(db_column="Quantity")),
                (
                    "unitprice",
                    models.DecimalField(
                        db_column="UnitPrice", decimal_places=2, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "bookorderitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customerid",
                    models.AutoField(
                        db_column="CustomerID", primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(db_column="FirstName", max_length=100)),
                ("lastname", models.CharField(db_column="LastName", max_length=100)),
                (
                    "email",
                    models.CharField(db_column="Email", max_length=150, unique=True),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, db_column="PhoneNumber", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Printingorder",
            fields=[
                (
                    "printingorderid",
                    models.AutoField(
                        db_column="PrintingOrderID", primary_key=True, serialize=False
                    ),
                ),
                ("orderdate", models.DateTimeField(db_column="OrderDate")),
                (
                    "completiondate",
                    models.DateTimeField(
                        blank=True, db_column="CompletionDate", null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(db_column="Quantity")),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "printingorder",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Printingpress",
            fields=[
                (
                    "printingpressid",
                    models.AutoField(
                        db_column="PrintingPressID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=150)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=150, null=True
                    ),
                ),
                (
                    "capacityperday",
                    models.PositiveIntegerField(
                        blank=True, db_column="CapacityPerDay", null=True
                    ),
                ),
                (
                    "machinetype",
                    models.CharField(
                        blank=True, db_column="MachineType", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "printingpress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "publisherid",
                    models.AutoField(
                        db_column="PublisherID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", max_length=150, unique=True),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="City", max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="Country", max_length=100, null=True
                    ),
                ),
                (
                    "contactemail",
                    models.CharField(
                        blank=True, db_column="ContactEmail", max_length=150, null=True
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, db_column="PhoneNumber", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "publisher",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "warehouseid",
                    models.AutoField(
                        db_column="WarehouseID", primary_key=True, serialize=False
                    ),
                ),
                ("location", models.CharField(db_column="Location", max_length=150)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, db_column="Capacity", null=True
                    ),
                ),
                (
                    "managername",
                    models.CharField(
                        blank=True, db_column="ManagerName", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "warehouse",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehousestock",
            fields=[
                (
                    "stockid",
                    models.AutoField(
                        db_column="StockID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, db_column="Quantity", null=True
                    ),
                ),
                (
                    "lastupdated",
                    models.DateTimeField(
                        blank=True, db_column="LastUpdated", null=True
                    ),
                ),
            ],
            options={
                "db_table": "warehousestock",
                "managed": False,
            },
        ),
    ]
